entrada: {}
saida: {}
pos1: {}
pos2: {}
prefixo: '&3[EDEventoSapo] '
selecioneUmaArea: '&cA arena ainda nao foi marcada'
arenaJaMarcada: '&cA arena ja foi marcada'
pos1Marcado: '&cPosicao 1 marcada com sucesso'
pos2Marcado: '&cPosicao 2 marcada com sucesso'
arenaRemovida: '&2Arena removida com sucesso'
arenaNaoMarcada: '&cA arena ainda nao foi marcada'
entradaMarcada: '&2Entrada marcada com sucesso'
entradaNaoMarcada: '&cA entrada ainda nao esta marcada'
saidaMarcada: '&2Saida do evento marcada com sucesso'
saidaNaoMarcada: '&cA saida ainda nao esta marcada'
teleportouEntrada: '&2Você se teleportou ate a entrada do evento'
entrouNoEvento: '&2Voce entrou no evento'
eventoNaoEstaAberto: '&cO evento nao esta aberto'
semPermissao: '&cVoce nao possui permissao para usar este comando'
naoExisteArena: '&cA arena ainda nao foi marcada'
minaPreparada: '&2Arena preparada com sucesso'
reloadCompleto: '&aReload completo'
jaIniciado: '&cEste evento ja foi iniciado, feche-o primeiro'
voceJaEstaParticipando: '&cVoce ja esta participando do evento'
eventoJaIniciado: '&cO evento ja foi iniciado'
eventoFinalizado: '&bO evento foi finalizado pelo staff %staff%'
esvazieoInventario: '&cEsvazie o inventario para poder entrar no evento'
naoEstaNoEvento: '&cVoce nao esta participando do evento'
saiuDoEvento: '&cVoce saiu do evento'
eventoRestrito: '&cVoce não pode utilizar nenhum item no evento'
eventoRestritoVoo: '&cVoce nao pode voar no evento'
acoesBloqueadas: '&cAçoes bloqueadas durante o evento'
ganhouEvento: '&b%player% Ganhou o evento'
desconectouEvento: '&c%player% Desconectou durante o evento'
saiuDoEvento: '&c%player% saiu do evento'
perdeuEvento: '&c%player% Perdeu o evento'
playersRestantes: '&bPlayers restantes &f:%players%'
ninguemGanhou: '&bNao houve ganhadores no evento'
chamadasEvento: 10
tempoChamadasSegundos: 20
chamadaEvento:
- ''
- '    &b&l&oEVENTO SAPO'
- '    &bIniciando evento em: &7&o%chamadas% &ochamadas'
- '    &bPara entrar utilize &7&o/eventosapo'
- '    &bJogadores no evento: &7&o%jogadores%'
- '    &bOBS: &n&oVenha de inventario vazio'
- ''
eventoIniciado:
- ''
- '    &b&l&oEVENTO SAPO INICIADO'
- '    &bEntrada bloqueada'
- '    &bJogadores no evento: &7&o%jogadores%'
- ''
argumentos:
- ''
- '&f&oUso correto:'
- '&b/eventosapo - &7&oEntra no evento'
- '&b/eventosapo sair - &7&oSai do evento'
- '&b/eventosapo criar - &7&oCria a arena do evento'
- '&b/eventosapo iniciar - &7&oAbre o evento'
- '&b/eventosapo fechar - &7&oFecha o evento'
- '&b/eventosapo preparar - &7&oPrepara a arena do evento'
- '&b/eventosapo setentrada - &7&oDefine a entrada do evento'
- '&b/eventosapo setsaida - &7&oDefine a saida do evento'
- '&b/eventosapo reload - &7&oReload no plugin'
- '&b/eventosapo entrada - &7&oTeleporta ate a entrada do evento'
- '&b/eventosapo remover - &7&oRemove a arena do evento'
- ''
